language: node_js
node_js: 11

# We cache the node_modules and other Yarn related files to speed up the build
cache: yarn

# Upgrade Yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

# Override default install command (it would run without --frozen-lockfile by default)
install:
  - yarn --frozen-lockfile

# Here we run all our tests
jobs:
  include:
    - stage: type checks and unit tests
      script: flow check && react-app-rewired test
    - stage: publish gh-pages
      script: yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: styleguide
        on:
          branch: master
    - stage: publish to Artifactory
      script: skip
      deploy:
        skip_cleanup: true # Keep all the artifacts generated on prev steps
        provider: script
        script: bash scripts/deploy.sh
        # The deploy script will run only on master
        on:
          branch: master
