language: node_js
node_js: 11
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - bash scripts/npmrc.sh $AUTOMATED_WRITE_AUTH > .npmrc
  - git update-index --assume-unchanged .npmrc
install:
  - yarn --frozen-lockfile
script:
  - yarn test:ci
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
