language: node_js
node_js: 11.1.0
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - bash scripts/npmrc.sh $AUTOMATED_WRITE_AUTH > .npmrc
script:
  - yarn test:ci
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
